#!/usr/bin/env python3
"""The LCO write-path: the LLM WRITES the Csound orchestra.

One prompt -> one inference against a curated library of real Csound idioms ->
one orchestra -> it runs. The library ORIENTS the model; it is not a menu the
model picks from and it is not assembled by Python. Morph, loop, mix, motion all
live IN the emitted Csound, because Csound is a programming language and the
model writes it.

BJ, 2026-07-19: "Es gibt: 1 Prompt. 1 LLM-Inferenz die Bibliotheken benutzt.
Daraus wird 1 Csound-Code fuer 1-3 Osc, die in sich morphen und was auch immer
tun: es ist 1 - EIN - Csound-Code der resultiert."

This module replaces the keys->prefab-emitter montage (`csound_orch.py`), which
was never authorised and is parked at tag `parked/keys-path-csound-20260721`.
Python's remaining job, and its whole job:

  1. assemble the prompt (library + host contract + platform invariants),
  2. call the model ONCE,
  3. wrap the returned body in the host scaffold,
  4. syntax-check it; on failure hand the compiler's own error back to the model
     and ask again (bounded), NEVER fall back to prefabricated code,
  5. return the orchestra.

LLM-first, no fallback: no model -> no oscillator. A prompt that cannot be
authored returns an honest ok=false, never a junk tone.
"""
import ctypes
import ctypes.util
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# Host scaffold constants -- these are the plugin's contract, not preferences.
KSMPS = 64
NCHNLS = 16          # == CsoundEngine::kMaxVoices
HEADROOM = 0.32      # bounds a single idiom's peak; the voice VCA/DCA shapes the rest

# How many times the model may see the compiler's error and try again. Each
# retry is a full re-authoring with the error in the user turn -- not a patch.
# The author is a 12B: most prompts land in one or two attempts, but a marginal
# tail (compound/modal prompts, and the odd greedy-but-not-deterministic Metal
# roll) needs the informative repair loop to run longer. With no fallback the
# alternative to another try is silence, so the ceiling is set where the loop
# reliably converges rather than as tight as it will usually go.
MAX_TRIES = int(os.environ.get("T5YNTH_LCO_MAX_TRIES", 6))



# ─────────────────────────────────────────────────────────────────────────────
# The library — the model's orientation
# ─────────────────────────────────────────────────────────────────────────────
# `backend/lco_library.json`, generated by `tools/lco_build_library.py` from
# `backend/dco_lexicon.json` plus the MEASURED anchors and the REAL Csound of the
# parked implementation (tag parked/keys-path-csound-20260721). Nothing here is
# hand-written: the code is what those ear-approved emitters actually produced,
# and the parameters, anchors and glosses are the lexicon's own.
#
# This is what BJ ordered (docs/LCO_CONCEPT.md §1): "Wir informieren ueber
# Parameter jeweils dieses Csound-Codes innerhalb seines Spektrums ... und
# Parametrisierungshinweise wie 'square ist sharp wenn Wert x = y, ist hollow
# wenn x = y'". The anchors ARE those hints, and they are shown as code at the
# anchor value, not only as prose.
#
# It is ORIENTATION, not a menu. The author adapts, combines and departs from it;
# nothing validates his reply against these keys, because he emits none.

LIBRARY_PATH = Path(__file__).resolve().parent / "lco_library.json"

_library_cache = None


def _load_library():
    global _library_cache
    if _library_cache is None:
        with open(LIBRARY_PATH, "r", encoding="utf-8") as fh:
            _library_cache = json.load(fh)
    return _library_cache


def _indent(code, pad="    "):
    return "\n".join(pad + l for l in (code or "").splitlines() if l.strip())


# A library is LOOKED UP IN, not recited. The lexicon's `surface_forms` are the
# index built for exactly that — the words that reach an entry. They select what
# the author gets to READ; they decide nothing about the sound, because the
# author still writes whatever it writes and may depart from every suggestion.
# Reciting all 29 instruments, 51 words and 17 motions cost 60,000 characters on
# every bake, of which a given prompt needs a handful.
_WORD = re.compile(r"[a-zà-ÿ0-9']+")

# When a prompt matches little or nothing, the author still needs orientation.
# These span the families (subtractive, FM, additive, modal) so an unmatched
# prompt is oriented rather than starved.
_STARTER = ("saw", "pwm", "fm_bell", "additive", "struck_bar")
_MAX_INSTRUMENTS = 8


def _index(lexicon_section):
    """surface form (and key) -> entry key."""
    idx = {}
    for e in lexicon_section:
        idx[e["key"].lower()] = e["key"]
        for sf in e.get("surface_forms", []):
            idx[str(sf).strip().lower()] = e["key"]
    return idx


def _lookup(prompt, index):
    """Entry keys whose surface forms appear in the prompt. Multi-word forms are
    matched against the raw text, single words against the tokenised prompt, so
    "electric piano" hits without "piano" alone dragging in a second entry."""
    text = " " + (prompt or "").lower() + " "
    words = set(_WORD.findall(text))
    hits = []
    for form, key in index.items():
        if key in hits:
            continue
        if " " in form or "-" in form:
            if form in text:
                hits.append(key)
        elif form in words:
            hits.append(key)
    return hits


_index_cache = None


def _indexes():
    global _index_cache
    if _index_cache is None:
        with open(Path(__file__).resolve().parent / "dco_lexicon.json",
                  encoding="utf-8") as fh:
            lex = json.load(fh)
        _index_cache = tuple(_index(lex[s])
                             for s in ("techniques", "adjectives", "motions"))
    return _index_cache


def select(prompt):
    """What this prompt pulls off the shelf, and what stays on it.

    Everything is still LISTED — the author sees the whole catalogue and can ask
    for nothing it doesn't contain. Only the entries the prompt reached are
    QUOTED in full, with their code, parameters and anchors."""
    lib = _load_library()
    t_idx, a_idx, m_idx = _indexes()
    t_hits = _lookup(prompt, t_idx)
    a_hits = set(_lookup(prompt, a_idx))
    m_hits = set(_lookup(prompt, m_idx))

    # Always give the author something to build from, and never more than a
    # handful: the matched instruments first, topped up from the starter set.
    chosen = list(t_hits)
    for k in _STARTER:
        if len(chosen) >= _MAX_INSTRUMENTS:
            break
        if k not in chosen:
            chosen.append(k)
    chosen = set(chosen[:_MAX_INSTRUMENTS])

    def split(entries, hits):
        return ([e for e in entries if e["key"] in hits],
                [e for e in entries if e["key"] not in hits])

    full_i, rest_i = split(lib["instruments"], chosen)
    full_a, rest_a = split(lib["adjectives"], a_hits)
    full_m, rest_m = split(lib["motions"], m_hits)
    return {"instruments": full_i, "adjectives": full_a, "motions": full_m,
            "catalogue": {"instruments": rest_i, "adjectives": rest_a,
                          "motions": rest_m},
            # The consultation, reported so the panel can SHOW it (the LCO
            # trace). `reached` is what the user's own words hit; `oriented_by`
            # is the _STARTER top-up the author was shown ANYWAY because the
            # prompt reached too few instruments. Keeping them apart is the whole
            # point: presenting a starter entry as something the prompt reached
            # would be the panel claiming an understanding that never happened.
            "consultation": {
                "reached": {"instruments": sorted(t_hits),
                            "adjectives": sorted(a_hits),
                            "motions": sorted(m_hits)},
                "oriented_by": sorted(chosen - set(t_hits)),
                "library_size": (len(lib["instruments"]) + len(lib["adjectives"])
                                 + len(lib["motions"])),
            }}


def _catalogue(out, lib, section, intro):
    """The shelf the author did not pull from — listed, so nothing is invisible.

    This is what makes the prompt a LIBRARY CONSULTATION rather than a recital:
    the author can see the whole vocabulary and knows what it is expected to be
    able to write, but only carries the weight of the entries this prompt
    reached."""
    rest = (lib.get("catalogue") or {}).get(section) or []
    if not rest:
        return
    out.append("")
    out.append(intro)
    for e in rest:
        why = (e.get("why") or "").strip()
        out.append(f"  {e['key']}" + (f" — {why}" if why else ""))


def render_library(sel=None):
    """The library as the author reads it: instruments with their real Csound,
    their parameters with measured ranges and named anchors, the anchor value
    shown AS CODE where the generator could emit it, then the sound words and
    motions the prompt reached, with the lines each word is responsible for."""
    lib = sel if sel is not None else _load_library()
    out = []

    out.append("## INSTRUMENTS")
    out.append("Real Csound, as this build actually produces it. Each block reads")
    out.append("`kfreq` and writes one signal. Adapt, combine, depart from them.")
    for it in lib["instruments"]:
        if not it.get("code") or it["code"].startswith(";"):
            continue
        out.append("")
        out.append(f"### {it['key']} — {it['why']}")
        out.append(_indent(it["code"]))
        for pname, spec in (it.get("params") or {}).items():
            rng = spec.get("range") or [0.0, 1.0]
            out.append(f"  parameter `{pname}` {rng[0]}..{rng[1]}, default "
                       f"{spec.get('default')}: {spec.get('note', '')}")
            for aname, a in (spec.get("anchors") or {}).items():
                out.append(f"    {pname}={a['value']} — {aname}: {a['gloss']}")
        # The anchor code shows which LINE moves with the character parameter. The
        # full body is already printed above, so quote only the lines that differ
        # from it at each anchor — the base plus five copies of the same twelve
        # lines is exactly the recital this file just stopped doing.
        base_lines = set((it.get("code") or "").splitlines())
        deltas = []
        for label, code in (it.get("anchor_code") or {}).items():
            changed = [l for l in code.splitlines() if l not in base_lines]
            if changed:
                deltas.append((label, changed))
        if deltas:
            out.append(f"  # how the code changes across `{next(iter(it['params']))}`:")
            for label, changed in deltas:
                out.append(f"    # {label}")
                for l in changed:
                    out.append(f"    {l.strip()}")

    _catalogue(out, lib, "instruments",
               "Also in the library, not quoted here. If one of these is what the "
               "prompt asks for, write it yourself in the same spirit:")

    out.append("")
    out.append("## SOUND WORDS (they belong IN the generation, not after it)")
    out.append("What each word means in code. Fold it into how the tone is MADE —")
    out.append("a word is a property of the generator, not an effect bolted on the end.")
    for adj in lib["adjectives"]:
        if not adj.get("code", "").strip():
            continue
        out.append("")
        out.append(f"### {adj['key']} — {adj['why']}")
        out.append(_indent(adj["code"]))

    _catalogue(out, lib, "adjectives",
               "Other words the library knows, without their code:")

    out.append("")
    out.append("## MOTION (movement is code: a free-running oscillator driving a parameter)")
    for mot in lib["motions"]:
        # The heading carries the KIND and the rate. The kind is the whole point of
        # the taxonomy -- does the movement return, is it regular, is it a movement
        # at all -- and the author is its only reader, so leaving it in the data
        # file would make the distinction invisible exactly where it must land.
        # The rate goes here too, not after the prose: a `why` ends in a full stop,
        # and appending ", around 0.19 Hz" to it reads as a typo.
        tag = ", ".join(x for x in (f"moves the {mot['moves']}" if mot.get("moves") else "",
                                    mot.get("kind") or "",
                                    f"around {mot['rate_hz']} Hz" if mot.get("rate_hz") else "")
                        if x)
        out.append("")
        out.append(f"### {mot['key']}{f' ({tag})' if tag else ''} — {mot['why']}")
        if mot.get("code", "").strip():
            out.append(_indent(mot["code"]))
        alt = mot.get("alt")
        if alt and (alt.get("code") or "").strip():
            out.append(f"  or, when {alt['when']}:")
            out.append(_indent(alt["code"]))

    _catalogue(out, lib, "motions", "Other movements the library knows:")
    return "\n".join(out)



# ─────────────────────────────────────────────────────────────────────────────
# The system prompt — library as orientation, host contract, platform invariants
# ─────────────────────────────────────────────────────────────────────────────
# The invariants are docs/LCO_CONCEPT.md §4. They are user-observable
# fundamentals: the oscillator is a SPECTRUM SOURCE, colour may travel but
# loudness may not, pitch belongs to the synth, and every sound MOVES unless the
# prompt asks for stillness.

_SYSTEM_HEAD = r"""You WRITE Csound orchestra code (Csound 6.18) for a synthesizer's oscillator. You are given a LIBRARY of real, working Csound idioms with measured parameter ranges and plain-language anchors. ADAPT and COMBINE them into the code that generates the sound the user describes. The library orients you; it is not a menu and you are not restricted to it.

WHAT YOU WRITE
Only the oscillator body: the lines that produce the raw signal. The host provides everything around it.

HARD RULES
- Read the pitch from `kfreq` (Hz, k-rate). It GLIDES; everything you write must track it. Never hardcode a pitch or a frequency number.
- Write your final audio into a variable named exactly `asig`.
- Define every variable before you use it, top to bottom. Give your variables distinct names; do not reuse a name for two things.
- Use only real Csound 6.18 opcodes. `vco2`'s imode is an INTEGER: 0 saw (every harmonic, 1/n), 2 pulse/square (odd harmonics, 1/n — `kpw` sets the duty), 4 triangle (odd harmonics, 1/n², much darker). Measured, not guessed: imode 10 is NOT triangle, it is another pulse. There is no `vco1`.
- An opcode call has NO equals sign: write `asig poscil 0.6, kfreq` — never `asig = poscil 0.6, kfreq`. `=` is only for arithmetic (`kx = 0.5 + klfo`).
- An opcode STATEMENT names its RESULT VARIABLE first, then the opcode: `ahi atone asig, 2200`. Two consequences you must never break: (a) an opcode that returns audio must have that result variable — `atone asig, 2200` on its own, with nothing on its left, does not compile; (b) the opcode NAME is not a value — never write `aprea = atone`, and never pass a bare `atone`/`rand`/`oscili` as another opcode's argument (`mode rand 0.06, kfreq, kQ` is wrong). To use an opcode's result in an expression, give it its own line first (`ahi atone asig, 2200` then `asig = asig + ahi * 0.3`), or use the functional form WITH parentheses around all arguments (`asig = asig * (1 + oscili(0.18, 5.5, giSine))`).
- `mode` is a resonant FILTER, not an oscillator: `ares mode aexc, kfreq, kQ`. Its first argument is an audio EXCITATION you must define on its OWN line first — `aexc rand 0.06, 0.5, 1` — never a bare opcode inlined (`mode rand 0.06, kfreq, kQ` is wrong). Build a bell/metal/drum bank by driving several `mode` lines from that SAME `aexc`, exactly as the struck_bar, drum_head and cymbal idioms do.
- `gbuzz` IS the additive oscillator: `ares gbuzz kamp, kcps, knh, klh, kmul, giCos` — `knh` is how MANY harmonics, `kmul` how fast they fall away (0 = fundamental only, 0.95 = a buzzing reed). Both are k-rate, so both may move over the note. But `gbuzz` normalises to PEAK, not loudness: raising `knh` or `kmul` makes the tone BRIGHTER AND QUIETER — up to 6 dB, which reads as the wrong thing entirely. Hold the level with the exact stack sum, once, and then set `knh`/`kmul` freely: `knrm = ((1-kmul^knh)/(1-kmul)) / sqrt((1-kmul^(2*knh))/(1-kmul*kmul)*0.5)` and pass `0.17 * knrm` as `kamp`. Measured over the whole range (1..24 harmonics, kmul 0.2..0.95, centroid 220..2241 Hz): 0.00 dB. Keep `kmul` below 1 — at 1 the expression divides by zero.
- You shape SPECTRUM and TIMBRE only. Do NOT write an amplitude envelope on the output (no linen, adsr, madsr, expon on the way to `asig`) — loudness belongs to the player's envelope. The COLOUR may travel over the note; the LOUDNESS may not. A tone that fades out on its own is wrong. There is exactly ONE exception, and only when the user asks for it by name: `tremolo` is a word for a loudness pulsation, so it pulses — regularly, shallowly, and never fading. When a colour movement would drag the level with it (a waveshaper, a filter sweep, a partial fading in), do not chase the level with a follower — build the bright version ONCE, match its level to the clean one ONCE, and then CROSSFADE between them: `adrv = tanh(asig * 4.4)`, `adrv balance adrv, asig, 1`, `asig = asig * (1 - kpos) + adrv * kpos` with `kpos` in 0..1. Every motion example below is built that way and holds the loudness inside 0.05 dB at every pitch, because nothing has to track the movement. Balancing the MOVING signal instead makes the follower run inside the waveform period on bass notes and cancel the very harmonics the drive just made.
- Keep `asig` near +-0.5 peak. The host applies its own headroom and voice gain.
- The sound MOVES by default: a sweep, a beat, a shimmer, a morph. Only write a standing tone if the user explicitly asks for something static or still.
- A LOOP is a free-running `oscili`/`phasor`/`lfo` that NEVER resets, driving a parameter or a crossfade. If the user asks for a loop or for something repeating, write a REPEATING trajectory — never a one-shot `linseg`, which moves once and then holds.
- "a > b" (equivalently "a into b", "a morphing into b", "a turning into b", "a transition from a to b", "a becomes b") is ONE voice that STARTS as a and BECOMES b across the note — a true crossfade, NOT two things. Build it in exactly this shape, and give a and b their OWN variables — never write your final `asig` more than once:
    asiga   <...>                          ; the first timbre, in its own variable
    asigb   <...>                          ; the second timbre, in its own variable
    kmorph  = min(knote / 2.0, 1)          ; 0 -> 1 over 2 s then holds (knote is in scope, seconds since the note began)
    asig    = asiga * (1 - kmorph) + asigb * kmorph
  Three ways this silently becomes "no transition at all" — each is WRONG for "a > b", never do them:
    (1) writing `asig` twice (`asig = <a>` … later `asig = <b>`): the second assignment ERASES the first, so only b is heard and everything above it is dead code. This is the most common mistake — a and b MUST meet in one crossfade line, not overwrite each other.
    (2) a static layer (`asig = <a> * kvol1 + <b> * kvol2`): that is a and b at once, forever — a LAYER, not a transition.
    (3) a bad `linseg` for the position (`linseg 0, 1, knote` passes a k-variable where linseg needs i-time CONSTANTS). Prefer `kmorph = min(knote / T, 1)`; if you must use linseg every argument is a constant — `kmorph linseg 0, 2, 1`.
  A REPEATING morph (a loop of a>b) drives kmorph from a free-running `oscili` instead of `min(knote…)`, so it sweeps back and forth forever.
- "a + b" means two layers sounding at once — the static mix of (2), correct ONLY when the user asked to layer, never as a substitute for a transition. You may layer up to THREE oscillators this way.
- Layer 1 must be scaled by `kvol1`, layer 2 by `kvol2`, layer 3 by `kvol3`, and each layer's pitch is `kfreq * koct1` / `koct2` / `koct3`. Those are the player's mix and octave knobs — a layer that ignores them cannot be mixed. With one layer, use `kvol1` and `kfreq * koct1`. In an "a > b" transition the two ends share `kvol1` and `kfreq * koct1` (it is one voice, not two layers).

AVAILABLE IN SCOPE
  kfreq  k-rate pitch in Hz (already glide-smoothed and limited)
  kvel   note velocity 0..1        kpres  pressure/aftertouch 0..1
  ktimb  timbre controller 0..1    knote  seconds since this note started
  ivoice this voice's number, 1..16 — DO NOT define it yourself, the host routes
         the output with it. Use it to give each voice its own phase or seed so a
         chord does not move in lockstep: `ivph = frac(ivoice * 0.6180339887)`.
  kvol1 kvol2 kvol3                per-layer mix (player knobs)
  koct1 koct2 koct3                per-layer octave multiplier (player knobs)
  giSine (sine table)  giCos (cosine table, for gbuzz/buzz)
  giCheb (Chebyshev transfer table)  giImp (short strike impulse table)

HOW TO ANSWER
FIRST THINK, in plain language, and write that thinking down — a short paragraph, not an essay:
  - What IS this sound? Which instrument, mechanism or physical body comes closest, and what in the library is nearest to it?
  - The words are a DESCRIPTION of a sound, not lookup keys. When the prompt names no instrument at all — "a dark growl", "rusty machinery", "like wet glass", "an angry insect" — this is where you work out what it would BE: what excites it, what resonates, what makes it dark or rough or restless. The library has no entry for most of what a player will ask for; you are expected to reason your way there from what the words describe, using the idioms as material.
  - What MOVES in it, and how fast?
THEN write the orchestra body, in exactly ONE fenced block:

```csound
<your Csound lines>
READING: <a short plain-language description of what you built, 5-12 words>
```

Inside the fence goes ONLY the oscillator body and that final READING line: no <CsoundSynthesizer>, no <CsInstruments>, no header (sr/ksmps/nchnls/0dbfs), no `instr`/`endin`, no `ftgen`, no score, no `out`/`outs`/`outch`. The host supplies all of it. Everything OUTSIDE the fence is your thinking and is discarded — so the fence must be there, and there must be exactly one.

LIBRARY (adapt and combine — do not simply copy one block):
"""


def system_prompt(prompt="", sel=None):
    """Head + the library entries this prompt reached. The full library stays on
    disk; what travels is the consultation.

    `sel` lets a caller that already ran select() (build_csound_response, which
    also REPORTS the consultation) reuse it, so the prompt the author sees and
    the consultation the panel shows can never describe different lookups."""
    return _SYSTEM_HEAD + "\n" + render_library(sel if sel is not None else select(prompt))


_REPAIR_HEAD = (
    "\n\nYour attempt did not compile. Csound reported {n_label}, and your next "
    "body must fix ALL of them AT ONCE without introducing a new one — fixing one "
    "line and breaking another only trades one error for the next:\n"
    "{errors}\n"
)
_REPAIR_TAIL = (
    "Csound's syntax errors are terse, so check EACH named line against the most "
    "common mechanical causes before rewriting:\n"
    "  - an opcode written with `=` — write `kx linseg ...`, never `kx = linseg ...`; `=` is only for arithmetic.\n"
    "  - an opcode sitting inside an arithmetic expression (`kpw = 0.02 + poscil 0.0042, 0.057`) — an opcode is NEVER a term in a `+`/`*`/`=`. Give it its OWN line first (`klfo poscil 0.0042, 0.057` then `kpw = 0.02 + klfo`), or use its functional form with parentheses around every argument (`kpw = 0.02 + poscil:k(0.0042, 0.057, giSine)`).\n"
    "  - an opcode with no result variable (`atone asig, 400` alone), or the opcode NAME used as a value (`asig = asig + atone`) — every opcode names its result first: `ahi atone asig, 400` then `asig = asig + ahi`.\n"
    "  - `mode` called without a named `aexc` excitation line before it.\n"
    "  - a variable used before it is defined, or your final signal not written into `asig`.\n"
    "Write the WHOLE body again, correctly. Do not explain the error."
)


def _repair_turn(seen_errors):
    """The repair user-turn built from EVERY distinct error seen so far, not just
    the latest. A single-error view makes the author oscillate: told to fix line
    A it rewrites and breaks line B, told to fix B it reintroduces A, and at
    temperature 0 that is a permanent 2-cycle no number of retries escapes
    (measured on "bright tone -> dark growl": 6/6 attempts alternated between an
    inline-`poscil` body and a bare-`atone` body). Showing all the constraints at
    once is a NEW turn the model has not been at, and it is still the model that
    writes the fix — Python names the compiler's complaints, never the Csound."""
    lines = "\n".join(f"  - {e}" for e in seen_errors)
    n_label = "this error" if len(seen_errors) == 1 else f"these {len(seen_errors)} errors"
    return _REPAIR_HEAD.format(n_label=n_label, errors=lines) + _REPAIR_TAIL


# ─────────────────────────────────────────────────────────────────────────────
# Sanitising the model's reply
# ─────────────────────────────────────────────────────────────────────────────
# The model is told not to emit a header, a score or an `instr`. It sometimes
# does anyway, and a stray header line would fight the host's own. Strip them
# rather than fail the authoring over a formality; anything that changes the
# SOUND is left untouched.

_STRIP = re.compile(
    r"^\s*(</?Cs\w+|sr\s*=|kr\s*=|ksmps\s*=|nchnls|0dbfs|instr\b|endin\b|"
    r"ftgen\b|\w+\s+ftgen\b|out\b|outs\b|outch\b|i\s+\d|f\s+\d|e\s*$)",
    re.IGNORECASE)

_FENCE = re.compile(r"```[A-Za-z0-9_+#-]*\s*\n(.*?)```", re.DOTALL)
_OUT_CALL = re.compile(r"\s*(?:out|outs|outch)\s+(?:\d+\s*,\s*)?(a\w+)", re.IGNORECASE)
_READING = re.compile(r"^\s*READING\s*:\s*(.+?)\s*$", re.IGNORECASE | re.MULTILINE)


def sanitize(raw):
    """Model reply -> (body, reading). Strips fences, the host's own lines and
    the READING line; recovers `asig` when the model wrote its output through
    `out`/`outch` under another name."""
    txt = raw or ""

    # Read READING from the WHOLE reply, BEFORE the fence is cut out. The author
    # is asked to put it inside the fence, but it costs nothing to also accept it
    # after — and cutting first would silently throw that one away.
    reading = ""
    rm = _READING.search(txt)
    if rm:
        reading = rm.group(1).strip()

    m = _FENCE.search(txt)
    if m:
        txt = m.group(1)
    elif "```" in txt:
        # An opened but never closed fence. Everything before it is the author's
        # thinking, which reaches the compiler as prose if it is not cut here.
        txt = re.sub(r"^[A-Za-z0-9_+#-]*[ \t]*\n", "", txt.split("```", 1)[1])
    txt = txt.replace("```", "")
    txt = _READING.sub("", txt)

    kept, captured_out = [], None
    for ln in txt.splitlines():
        s = ln.rstrip()
        if not s.strip():
            continue
        mo = _OUT_CALL.match(s)
        if mo:
            captured_out = mo.group(1)
        if _STRIP.match(s):
            continue
        kept.append(s)
    body = "\n".join(kept)
    # The model routed its signal to the output under another name: keep the
    # sound and give the host the variable it needs.
    if not re.search(r"^\s*asig\b", body, re.MULTILINE) and captured_out and captured_out != "asig":
        body += f"\n  asig = {captured_out}"
    return body, reading


# ─────────────────────────────────────────────────────────────────────────────
# The host scaffold — everything around the authored body
# ─────────────────────────────────────────────────────────────────────────────
# Unchanged from the shipped contract: sr is substituted by the engine at its
# real rate, ksmps=64, nchnls=16 (one channel per voice), one numeric `instr 1`
# with p4 = voice index, six named control channels per voice read via chnget,
# and 16 always-on score instances.

_HEAD = (
    "<CsoundSynthesizer>\n<CsOptions>\n-n -d\n</CsOptions>\n<CsInstruments>\n"
    "sr = %SR%\n"
    f"ksmps = {KSMPS}\n"
    f"nchnls = {NCHNLS}\n"
    "0dbfs = 1\n"
    "giSine ftgen 1, 0, 65536, 10, 1\n"
    # gbuzz reads a COSINE table (its harmonics are cosines); a sine table here
    # would phase-shift every harmonic against the fundamental.
    "giCos  ftgen 2, 0, 65536, 11, 1\n"
    # GEN13 Chebyshev TRANSFER function, odd harmonics with alternating signs:
    # odd-only is antisymmetric, so f(0)=0 and the shaper is DC-free at EVERY
    # drive level and can be swept freely; alternating signs leave each
    # harmonic's magnitude untouched (a sign is a phase) while the peak sums to
    # 0.71 instead of 2.01 — 10 dB of crest given back.
    "giCheb ftgen 3, 0, 8193, 13, 1, 1, 0, 1, 0, -0.5, 0, 0.28, 0, -0.15, 0, 0.08\n"
    # Short decaying harmonic burst: the mallet contact for struck models, which
    # take their strike argument as a TABLE NUMBER, not a scalar.
    "giImp  ftgen 4, 0, 256, 10, 1, 0.5, 0.3, 0.2, 0.1\n"
    # Starting values for the player's mix/octave knobs. The plugin overwrites
    # these from its parameters on the next block; an offline render or a host
    # that never writes them plays exactly what was authored.
    "chnset 1.0000, \"osc1vol\"\n"
    "chnset 1.0000, \"osc1oct\"\n"
    "chnset 1.0000, \"osc2vol\"\n"
    "chnset 1.0000, \"osc2oct\"\n"
    "chnset 1.0000, \"osc3vol\"\n"
    "chnset 1.0000, \"osc3oct\"\n"
    "\n"
    "instr 1\n"
    "  ivoice   = p4\n"
    "  Sgate    sprintf \"gate%d\", ivoice\n"
    "  Sfreq    sprintf \"freq%d\", ivoice\n"
    "  Svel     sprintf \"vel%d\", ivoice\n"
    "  Spres    sprintf \"pres%d\", ivoice\n"
    "  Stimb    sprintf \"timb%d\", ivoice\n"
    "  Strig    sprintf \"trig%d\", ivoice\n"
    "  kgateraw chnget Sgate\n"
    "  kfreqraw chnget Sfreq\n"
    "  kvel     chnget Svel\n"
    "  kpres    chnget Spres\n"
    "  ktimb    chnget Stimb\n"
    "  ktrig    chnget Strig\n"
    "  kvol1    chnget \"osc1vol\"\n"
    "  koct1    chnget \"osc1oct\"\n"
    "  kvol2    chnget \"osc2vol\"\n"
    "  koct2    chnget \"osc2oct\"\n"
    "  kvol3    chnget \"osc3vol\"\n"
    "  koct3    chnget \"osc3oct\"\n"
    "  kgate    portk kgateraw, 0.001\n"
    "  kfreq    limit kfreqraw, 20, 12000\n"
    "  kpresGain = 1.0 + 0.15 * kpres\n"
    # Seconds since THIS note, for anything that shapes timbre over the note.
    # init 0 rather than a settled value: a note whose gate and trig are already
    # high before the first k-cycle gives changed2 no edge to fire on, so a
    # counter starting anywhere else would sit frozen forever.
    "  knote    init 0\n"
    "  if changed2(ktrig) == 1 then\n"
    "    knote  = 0\n"
    "  endif\n"
    "  knote    = knote + 1/kr\n\n"
)

_TAIL = (
    "\n"
    f"  aout     = asig * kgate * kvel * kpresGain * {HEADROOM}\n"
    "  aout     clip aout, 0, 0.95, 0.85    ; final soft peak safety: transparent\n"
    "                                       ; below ~0.8, asymptotes ~0.88 above,\n"
    "                                       ; bounds ANY op stack / crest / host gain\n"
    "  outch    ivoice, aout\n"
    "endin\n"
    "</CsInstruments>\n<CsScore>\n"
)

_SCORE = "".join(f"i 1 0 360000 {v}\n" for v in range(1, NCHNLS + 1)) \
         + "e 360000\n</CsScore>\n</CsoundSynthesizer>\n"


def wrap(body):
    """Authored body -> the full orchestra the engine compiles."""
    indented = "\n".join(("  " + l) if not l.startswith(" ") else l
                         for l in body.splitlines())
    return _HEAD + indented + _TAIL + _SCORE


# ─────────────────────────────────────────────────────────────────────────────
# The compile gate
# ─────────────────────────────────────────────────────────────────────────────

_ANSI = re.compile(r"\x1b\[[0-9;]*m")
# The CLI echoes its `>>> … <<<` source line one character at a time, with an SGR
# escape between each and a raw NUL at the parser's error position. Stripping
# only the escapes leaves that NUL in the quoted line — which then goes into the
# repair turn (a stray control byte mid-line for the author) and into the JSON
# error, where juce::String truncates at it and the user loses the rest of the
# message. The in-process compiler has no such marker, so this is also what keeps
# the two paths' diagnostics identical.
_CTRL = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")
_ERR_LINE = re.compile(r"\berror:", re.IGNORECASE)
# Csound points at the offending source two ways: a bare "Line N" for semantic
# errors, and a ">>> <the line> <<<" echo for parse errors. Read both.
_LINE_NO = re.compile(r"^\s*Line\s+(\d+)\s*$", re.IGNORECASE)
_ECHO = re.compile(r">>>\s*(.*?)\s*<<<")
# Where the authored body starts inside the wrapped CSD, so a line number in
# Csound's message can be mapped back to a line the AUTHOR actually wrote. The
# model never sees the wrapper; telling it "line 49" of a file it did not write
# is worse than telling it nothing.
_BODY_OFFSET = _HEAD.count("\n")


# Where the compiler actually lives.
#
# It was a bare "csound" resolved through $PATH — and the backend inherits the
# PATH of the app that forked it. A plugin or standalone launched from Finder /
# `open` gets launchd's (/usr/bin:/bin:/usr/sbin:/sbin), which is exactly where
# Homebrew's /opt/homebrew/bin is NOT. The lookup raised FileNotFoundError,
# syntax_check read that as "unverified but fine", and EVERY first draft went to
# the engine unchecked: the repair loop never ran a single round and the host
# reported the compile error this gate exists to catch.
#
# Two ways to reach a compiler, in this order:
#
#   1. the CLI, when one is installed — a separate process, so a Csound abort
#      cannot take down a backend holding a multi-GB model in memory;
#   2. CsoundLib64 itself through ctypes. The ENGINE only ever needed the
#      library (CsoundEngine.cpp: csoundCompileCsdText), and that is all
#      tools/bundle_csound_macos.sh ships into Contents/libs — so a gate that
#      insisted on the CLI would go dark on exactly the installs the bundling
#      exists to serve, while the engine next to it compiled fine.
#
# Both are the same compiler the engine runs, which is the point: a gate that
# is not the thing that later judges is not a gate.
_CSOUND_CANDIDATES = (
    "/opt/homebrew/bin/csound",
    "/usr/local/bin/csound",
    "/opt/homebrew/opt/csound/bin/csound",
    "/Library/Frameworks/CsoundLib64.framework/Versions/Current/Resources/bin/csound",
    "/usr/bin/csound",
)

_CSOUND_LIB_CANDIDATES = (
    "/opt/homebrew/opt/csound/Frameworks/CsoundLib64.framework/CsoundLib64",
    "/Library/Frameworks/CsoundLib64.framework/CsoundLib64",
    "/usr/local/lib/libcsound64.dylib",
    "libcsound64.so.6.0",
    "libcsound64.so",
)

NO_COMPILER = ("no Csound compiler reachable: the orchestra cannot be checked "
               "before it reaches the engine (install Csound, or point "
               "T5YNTH_CSOUND at the csound binary)")


class CompilerUnavailable(Exception):
    """The environment cannot compile anything. NOT an authoring failure: it must
    never be shown to the model as a Csound diagnostic, and no retry can fix it."""


def _executable(path):
    return bool(path) and os.path.isfile(path) and os.access(path, os.X_OK)


def _csound_binary():
    """Absolute path to a usable Csound CLI, or None.

    T5YNTH_CSOUND is validated like any other candidate: a directory, a
    non-executable file or a leftover bare "csound" would otherwise be returned
    as a compiler, and the failure would surface six inferences later as the
    author's fault instead of the setting's."""
    explicit = os.environ.get("T5YNTH_CSOUND")
    if explicit:
        if _executable(explicit):
            return explicit
        resolved = shutil.which(explicit)
        if _executable(resolved):
            return resolved
        return None
    found = shutil.which("csound")
    if _executable(found):
        return found
    for cand in _CSOUND_CANDIDATES:
        if _executable(cand):
            return cand
    return None


def _bundled_csound_libs():
    """CsoundLib64 inside the host app bundle, if the backend runs from one.
    tools/bundle_csound_macos.sh flattens it to <App>.app/Contents/libs/CsoundLib64
    and rewrites every load command to @loader_path/../libs."""
    here = Path(getattr(sys, "_MEIPASS", "") or os.path.abspath(sys.argv[0]))
    for parent in [here] + list(here.parents):
        if parent.name == "Contents":
            yield str(parent / "libs" / "CsoundLib64")
            return


def _csound_library():
    """A loaded CsoundLib64 handle with the entry points the gate needs, or None."""
    global _csound_lib_cache
    if _csound_lib_cache is not False:
        return _csound_lib_cache

    _csound_lib_cache = None
    explicit = os.environ.get("T5YNTH_CSOUND_LIB")
    found = ctypes.util.find_library("CsoundLib64") or ctypes.util.find_library("csound64")
    for cand in ([explicit] if explicit else []) + list(_bundled_csound_libs()) \
                + list(_CSOUND_LIB_CANDIDATES) + ([found] if found else []):
        try:
            lib = ctypes.CDLL(cand)
            lib.csoundCreate.restype = ctypes.c_void_p
            lib.csoundCreate.argtypes = [ctypes.c_void_p]
            lib.csoundCompileCsdText.restype = ctypes.c_int
            lib.csoundCompileCsdText.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
            lib.csoundSetOption.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
            lib.csoundCreateMessageBuffer.argtypes = [ctypes.c_void_p, ctypes.c_int]
            lib.csoundGetMessageCnt.argtypes = [ctypes.c_void_p]
            lib.csoundGetMessageCnt.restype = ctypes.c_int
            lib.csoundGetFirstMessage.argtypes = [ctypes.c_void_p]
            lib.csoundGetFirstMessage.restype = ctypes.c_char_p
            lib.csoundPopFirstMessage.argtypes = [ctypes.c_void_p]
            lib.csoundDestroyMessageBuffer.argtypes = [ctypes.c_void_p]
            lib.csoundDestroy.argtypes = [ctypes.c_void_p]
        except (OSError, AttributeError):
            continue
        _csound_lib_cache = lib
        break
    return _csound_lib_cache


_csound_lib_cache = False   # False = not looked for yet; None = looked, absent


def _check_via_library(csd):
    """(ok, log) from CsoundLib64 in-process — the engine's own call sequence
    (CsoundEngine.cpp:374-388): create, -n -d, compile the CSD text, read the
    message queue. No csoundStart: nothing here is meant to make sound."""
    lib = _csound_library()
    if lib is None:
        raise CompilerUnavailable(NO_COMPILER)
    cs = lib.csoundCreate(None)
    if not cs:
        raise CompilerUnavailable(NO_COMPILER)
    try:
        lib.csoundCreateMessageBuffer(cs, 0)   # queue-only, not to our stderr
        lib.csoundSetOption(cs, b"-n")
        lib.csoundSetOption(cs, b"-d")
        # Quiet the per-note statistics. Csound still prints its score-teardown
        # summary straight to stderr from csoundDestroy (after the message
        # buffer is gone), so backend_stderr.log picks up a few hundred bytes
        # per check on this path — noise, not a failure.
        lib.csoundSetOption(cs, b"-m0")
        rc = lib.csoundCompileCsdText(cs, csd.encode("utf-8"))
        parts = []
        for _ in range(lib.csoundGetMessageCnt(cs)):
            msg = lib.csoundGetFirstMessage(cs)
            if msg:
                parts.append(msg.decode("utf-8", "replace"))
            lib.csoundPopFirstMessage(cs)
        return rc == 0, "".join(parts)
    finally:
        lib.csoundDestroyMessageBuffer(cs)
        lib.csoundDestroy(cs)


def _explain(log, orchestra):
    """Csound's own complaint, plus the line of the AUTHORED body it points at.

    Csound reports positions in the wrapped CSD. The author wrote only the body
    and has never seen the wrapper, so a bare "Line 49" is unusable to it —
    quoting its own line back is what makes the repair round actually repair.
    """
    msgs, quoted = [], []
    csd_lines = orchestra.splitlines()
    for ln in _CTRL.sub("", _ANSI.sub("", log)).splitlines():
        if _ERR_LINE.search(ln):
            # drop Csound's "from file /tmp/....csd (1)," prefix: a temp path is
            # noise in the repair turn, and the author cannot act on it.
            msgs.append(re.sub(r"^.*?from file .*?,\s*", "", ln.strip()))
            continue
        e = _ECHO.search(ln)
        if e and e.group(1).strip():
            quoted.append(f"your line: {e.group(1).strip()}")
            continue
        m = _LINE_NO.match(ln)
        if m:
            n = int(m.group(1))
            src = csd_lines[n - 1].strip() if 0 < n <= len(csd_lines) else ""
            if src and n > _BODY_OFFSET:
                quoted.append(f'your line: {src}')
    if not msgs:
        tail = [l for l in log.strip().splitlines() if l.strip()]
        msgs = [tail[-1]] if tail else ["csound failed without a message"]
    # de-duplicate while keeping order: the same error is often echoed per pass
    seen, parts = set(), []
    for part in msgs + quoted:
        if part not in seen:
            seen.add(part)
            parts.append(part)
    return "; ".join(parts[:4])


def syntax_check(orchestra):
    """(ok, first_error). Runs the real compiler over the real orchestra, so the
    gate is Csound's own verdict rather than a parser of ours guessing at one.
    sr is substituted for the check only.

    Raises CompilerUnavailable when there is no compiler to ask. That is an
    environment fault, not an authoring one: it must not be dressed up as a
    Csound diagnostic and fed back to the model, and no retry can repair it."""
    csd = orchestra.replace("%SR%", "44100")
    binary = _csound_binary()
    if binary is not None:
        try:
            return _check_via_cli(binary, csd, orchestra)
        except OSError as exc:
            # The binary vanished between lookup and run, or no process could be
            # spawned at all (ENOMEM/EMFILE next to a resident multi-GB model).
            # The in-process compiler needs no fork, so try it before giving up —
            # refusing to author while a working Csound sits in this very process
            # would be the wrong answer to a fork that failed.
            spawn_error = f"could not run {binary}: {exc}"
    else:
        spawn_error = None

    try:
        ok, log = _check_via_library(csd)
    except CompilerUnavailable:
        # Neither route worked. Prefer the spawn failure's own errno over the
        # generic "nothing installed": one of them is actionable.
        if spawn_error:
            raise CompilerUnavailable(spawn_error) from None
        raise
    return (True, "") if ok else (False, _explain(log, orchestra))


def _check_via_cli(binary, csd, orchestra):
    """(ok, first_error) from the Csound CLI in its own process. Lets OSError
    through: the caller decides whether an unspawnable compiler is fatal."""
    # encoding is explicit: an authored comment can carry any codepoint, and the
    # platform default (cp1252 on Windows) would raise mid-write, leaking the
    # temp file and escaping every handler here as a bare ValueError. The
    # in-process path encodes UTF-8, so this also keeps the two paths agreeing.
    fh = tempfile.NamedTemporaryFile("w", suffix=".csd", delete=False,
                                     encoding="utf-8", errors="replace")
    path = fh.name
    try:
        with fh:
            fh.write(csd)
        r = subprocess.run([binary, "--syntax-check-only", path],
                           capture_output=True, text=True, timeout=90)
        if r.returncode == 0:
            return True, ""
        return False, _explain((r.stderr or "") + (r.stdout or ""), orchestra)
    except subprocess.TimeoutExpired:
        return False, "csound syntax check timed out"
    finally:
        try:
            os.unlink(path)
        except OSError:
            pass


# ─────────────────────────────────────────────────────────────────────────────
# The entry point
# ─────────────────────────────────────────────────────────────────────────────

def build_csound_response(text, llm, correction="", previous=""):
    """Prompt -> live Csound orchestra. The REAL pipeline entry
    (pipe_inference mode=="csound" calls this).

    ONE inference writes the orchestra body against the library; the compiler
    checks it; a failure goes back to the model with Csound's own error, up to
    MAX_TRIES. There is NO fallback: if the model cannot produce a compiling
    orchestra, this returns ok=false and the LCO stays silent, exactly as
    docs/LCO_CONCEPT.md §4 requires ("no LLM, no oscillator").

    ``llm`` is the caller-injected ``(text, system_prompt, max_new_tokens) ->
    str`` callable. Returns the {ok, orchestra, reading, error} shape the C++
    PipeInference parses.

    ``correction``/``previous`` are accepted for wire compatibility and are
    appended to the user turn when present (the self-listen loop is currently
    deactivated and sends neither).
    """
    prompt = (text or "").strip()
    if not prompt:
        return {"ok": False, "error": "empty prompt"}

    # Ask once, before spending inferences: with nothing to compile against,
    # every attempt would fail identically at the gate, and the honest answer is
    # already available. An uncapped 12B authoring turn is not cheap enough to
    # burn six of on a question the environment has already answered.
    if _csound_binary() is None and _csound_library() is None:
        return {"ok": False, "error": NO_COMPILER}

    user_turn = prompt
    if correction:
        user_turn = (f"{prompt}\n\nThe previous attempt was described as: "
                     f"{previous}\nCorrect it: {correction}")

    # ONE selection, used twice: it builds the author's prompt AND is reported
    # back as the consultation the panel shows. Selecting twice would let the two
    # drift apart, and a trace that describes a lookup the author never got is
    # worse than no trace.
    sel = select(prompt)
    sysp = system_prompt(prompt, sel)
    attempts = []
    seen_errors = []   # distinct errors, in first-seen order — the whole repair context
    turn = user_turn
    for attempt in range(1, MAX_TRIES + 1):
        # No token cap: the orchestra is as long as the sound needs. A cap here
        # would cut the body mid-line, and a truncated generation is not an
        # error — it would arrive as a syntax failure with no cause to show.
        raw = llm(turn, sysp, None)
        body, reading = sanitize(raw)
        if not body.strip():
            attempts.append("the model returned no code")
            if "you returned no code at all" not in seen_errors:
                seen_errors.append("you returned no code at all")
            turn = user_turn + _repair_turn(seen_errors)
            continue

        orchestra = wrap(body)
        try:
            ok, err = syntax_check(orchestra)
        except CompilerUnavailable as exc:
            # The compiler went away mid-run (or could not be spawned). Stop:
            # re-prompting the author with an environment fault would ask it to
            # repair code that may be perfectly good, five more times.
            return {"ok": False, "error": str(exc), "attempts": attempt}
        if ok:
            return {"ok": True, "orchestra": orchestra,
                    "reading": reading or _fallback_reading(body),
                    # The panel's transparency surface. Under the write-path the
                    # honest answer to "what did the machine build?" is the code
                    # the model actually wrote -- not a list of keys it picked,
                    # because it picks none.
                    "params_text": body,
                    # The rest of the authoring trace, so the panel can show HOW
                    # this orchestra came about and not only WHAT came out. Both
                    # are records of what actually happened -- the author is
                    # asked for no explanation of itself and none is invented
                    # here (BJ 2026-07-24: "nur was ohnehin passiert ist").
                    "consultation": sel["consultation"],
                    # The compiler errors this body had to be repaired past, in
                    # first-seen order; empty when it compiled on the first try.
                    # Shown, not hidden: an orchestra that took four rounds to
                    # stand up is a different fact about the machine than one
                    # that landed immediately, and only the panel can say so.
                    "repairs": list(seen_errors),
                    "attempts": attempt}
        attempts.append(err)
        if err not in seen_errors:
            seen_errors.append(err)
        turn = user_turn + _repair_turn(seen_errors)

    # Report every DISTINCT error, not just the last one. The two cases look the
    # same from outside and need opposite responses: six times the same complaint
    # is the library orienting the author wrongly and is fixable here; six
    # different ones is a prompt this author cannot hold together. With only the
    # last error visible, a systematic gap reads as bad luck.
    seen, distinct = set(), []
    for e in attempts:
        if e not in seen:
            seen.add(e)
            distinct.append(e)
    if not distinct:
        detail = "unknown"
    elif len(distinct) == 1:
        detail = f"the same error every time: {distinct[0]}"
    else:
        detail = " | ".join(distinct)
    return {"ok": False,
            "error": "the author could not write a compiling orchestra after "
                     f"{MAX_TRIES} attempts: {detail}",
            "attempts": MAX_TRIES}


def _fallback_reading(body):
    """A reading when the model omitted its READING line. Names the opcodes it
    actually used — a true, if plain, statement about what is running."""
    seen = []
    for op in ("vco2", "foscili", "gbuzz", "buzz", "mode", "oscili", "phasor",
               "rand", "reson", "tablei", "tanh", "balance"):
        if re.search(rf"\b{op}\b", body) and op not in seen:
            seen.append(op)
    return ("built from " + ", ".join(seen[:5])) if seen else "authored orchestra"
