#!/usr/bin/env python3
"""The LCO write-path: the LLM WRITES the Csound orchestra.

One prompt -> one inference against a curated library of real Csound idioms ->
one orchestra -> it runs. The library ORIENTS the model; it is not a menu the
model picks from and it is not assembled by Python. Morph, loop, mix, motion all
live IN the emitted Csound, because Csound is a programming language and the
model writes it.

BJ, 2026-07-19: "Es gibt: 1 Prompt. 1 LLM-Inferenz die Bibliotheken benutzt.
Daraus wird 1 Csound-Code fuer 1-3 Osc, die in sich morphen und was auch immer
tun: es ist 1 - EIN - Csound-Code der resultiert."

This module replaces the keys->prefab-emitter montage (`csound_orch.py`), which
was never authorised and is parked at tag `parked/keys-path-csound-20260721`.
Python's remaining job, and its whole job:

  1. assemble the prompt (library + host contract + platform invariants),
  2. call the model ONCE,
  3. wrap the returned body in the host scaffold,
  4. syntax-check it; on failure hand the compiler's own error back to the model
     and ask again (bounded), NEVER fall back to prefabricated code,
  5. return the orchestra.

LLM-first, no fallback: no model -> no oscillator. A prompt that cannot be
authored returns an honest ok=false, never a junk tone.
"""
import json
import os
import re
import subprocess
import tempfile
from pathlib import Path

# Host scaffold constants -- these are the plugin's contract, not preferences.
KSMPS = 64
NCHNLS = 16          # == CsoundEngine::kMaxVoices
HEADROOM = 0.32      # bounds a single idiom's peak; the voice VCA/DCA shapes the rest

# How many times the model may see the compiler's error and try again. Each
# retry is a full re-authoring with the error in the user turn -- not a patch.
# The author is a 12B: most prompts land in one or two attempts, but a marginal
# tail (compound/modal prompts, and the odd greedy-but-not-deterministic Metal
# roll) needs the informative repair loop to run longer. With no fallback the
# alternative to another try is silence, so the ceiling is set where the loop
# reliably converges rather than as tight as it will usually go.
MAX_TRIES = int(os.environ.get("T5YNTH_LCO_MAX_TRIES", 6))



# ─────────────────────────────────────────────────────────────────────────────
# The library — the model's orientation
# ─────────────────────────────────────────────────────────────────────────────
# `backend/lco_library.json`, generated by `tools/lco_build_library.py` from
# `backend/dco_lexicon.json` plus the MEASURED anchors and the REAL Csound of the
# parked implementation (tag parked/keys-path-csound-20260721). Nothing here is
# hand-written: the code is what those ear-approved emitters actually produced,
# and the parameters, anchors and glosses are the lexicon's own.
#
# This is what BJ ordered (docs/LCO_CONCEPT.md §1): "Wir informieren ueber
# Parameter jeweils dieses Csound-Codes innerhalb seines Spektrums ... und
# Parametrisierungshinweise wie 'square ist sharp wenn Wert x = y, ist hollow
# wenn x = y'". The anchors ARE those hints, and they are shown as code at the
# anchor value, not only as prose.
#
# It is ORIENTATION, not a menu. The author adapts, combines and departs from it;
# nothing validates his reply against these keys, because he emits none.

LIBRARY_PATH = Path(__file__).resolve().parent / "lco_library.json"

_library_cache = None


def _load_library():
    global _library_cache
    if _library_cache is None:
        with open(LIBRARY_PATH, "r", encoding="utf-8") as fh:
            _library_cache = json.load(fh)
    return _library_cache


def _indent(code, pad="    "):
    return "\n".join(pad + l for l in (code or "").splitlines() if l.strip())


# A library is LOOKED UP IN, not recited. The lexicon's `surface_forms` are the
# index built for exactly that — the words that reach an entry. They select what
# the author gets to READ; they decide nothing about the sound, because the
# author still writes whatever it writes and may depart from every suggestion.
# Reciting all 29 instruments, 51 words and 17 motions cost 60,000 characters on
# every bake, of which a given prompt needs a handful.
_WORD = re.compile(r"[a-zà-ÿ0-9']+")

# When a prompt matches little or nothing, the author still needs orientation.
# These span the families (subtractive, FM, additive, modal) so an unmatched
# prompt is oriented rather than starved.
_STARTER = ("saw", "pwm", "fm_bell", "additive", "struck_bar")
_MAX_INSTRUMENTS = 8


def _index(lexicon_section):
    """surface form (and key) -> entry key."""
    idx = {}
    for e in lexicon_section:
        idx[e["key"].lower()] = e["key"]
        for sf in e.get("surface_forms", []):
            idx[str(sf).strip().lower()] = e["key"]
    return idx


def _lookup(prompt, index):
    """Entry keys whose surface forms appear in the prompt. Multi-word forms are
    matched against the raw text, single words against the tokenised prompt, so
    "electric piano" hits without "piano" alone dragging in a second entry."""
    text = " " + (prompt or "").lower() + " "
    words = set(_WORD.findall(text))
    hits = []
    for form, key in index.items():
        if key in hits:
            continue
        if " " in form or "-" in form:
            if form in text:
                hits.append(key)
        elif form in words:
            hits.append(key)
    return hits


_index_cache = None


def _indexes():
    global _index_cache
    if _index_cache is None:
        with open(Path(__file__).resolve().parent / "dco_lexicon.json",
                  encoding="utf-8") as fh:
            lex = json.load(fh)
        _index_cache = tuple(_index(lex[s])
                             for s in ("techniques", "adjectives", "motions"))
    return _index_cache


def select(prompt):
    """What this prompt pulls off the shelf, and what stays on it.

    Everything is still LISTED — the author sees the whole catalogue and can ask
    for nothing it doesn't contain. Only the entries the prompt reached are
    QUOTED in full, with their code, parameters and anchors."""
    lib = _load_library()
    t_idx, a_idx, m_idx = _indexes()
    t_hits = _lookup(prompt, t_idx)
    a_hits = set(_lookup(prompt, a_idx))
    m_hits = set(_lookup(prompt, m_idx))

    # Always give the author something to build from, and never more than a
    # handful: the matched instruments first, topped up from the starter set.
    chosen = list(t_hits)
    for k in _STARTER:
        if len(chosen) >= _MAX_INSTRUMENTS:
            break
        if k not in chosen:
            chosen.append(k)
    chosen = set(chosen[:_MAX_INSTRUMENTS])

    def split(entries, hits):
        return ([e for e in entries if e["key"] in hits],
                [e for e in entries if e["key"] not in hits])

    full_i, rest_i = split(lib["instruments"], chosen)
    full_a, rest_a = split(lib["adjectives"], a_hits)
    full_m, rest_m = split(lib["motions"], m_hits)
    return {"instruments": full_i, "adjectives": full_a, "motions": full_m,
            "catalogue": {"instruments": rest_i, "adjectives": rest_a,
                          "motions": rest_m}}


def _catalogue(out, lib, section, intro):
    """The shelf the author did not pull from — listed, so nothing is invisible.

    This is what makes the prompt a LIBRARY CONSULTATION rather than a recital:
    the author can see the whole vocabulary and knows what it is expected to be
    able to write, but only carries the weight of the entries this prompt
    reached."""
    rest = (lib.get("catalogue") or {}).get(section) or []
    if not rest:
        return
    out.append("")
    out.append(intro)
    for e in rest:
        why = (e.get("why") or "").strip()
        out.append(f"  {e['key']}" + (f" — {why}" if why else ""))


def render_library(sel=None):
    """The library as the author reads it: instruments with their real Csound,
    their parameters with measured ranges and named anchors, the anchor value
    shown AS CODE where the generator could emit it, then the sound words and
    motions the prompt reached, with the lines each word is responsible for."""
    lib = sel if sel is not None else _load_library()
    out = []

    out.append("## INSTRUMENTS")
    out.append("Real Csound, as this build actually produces it. Each block reads")
    out.append("`kfreq` and writes one signal. Adapt, combine, depart from them.")
    for it in lib["instruments"]:
        if not it.get("code") or it["code"].startswith(";"):
            continue
        out.append("")
        out.append(f"### {it['key']} — {it['why']}")
        out.append(_indent(it["code"]))
        for pname, spec in (it.get("params") or {}).items():
            rng = spec.get("range") or [0.0, 1.0]
            out.append(f"  parameter `{pname}` {rng[0]}..{rng[1]}, default "
                       f"{spec.get('default')}: {spec.get('note', '')}")
            for aname, a in (spec.get("anchors") or {}).items():
                out.append(f"    {pname}={a['value']} — {aname}: {a['gloss']}")
        # The anchor code shows which LINE moves with the character parameter. The
        # full body is already printed above, so quote only the lines that differ
        # from it at each anchor — the base plus five copies of the same twelve
        # lines is exactly the recital this file just stopped doing.
        base_lines = set((it.get("code") or "").splitlines())
        deltas = []
        for label, code in (it.get("anchor_code") or {}).items():
            changed = [l for l in code.splitlines() if l not in base_lines]
            if changed:
                deltas.append((label, changed))
        if deltas:
            out.append(f"  # how the code changes across `{next(iter(it['params']))}`:")
            for label, changed in deltas:
                out.append(f"    # {label}")
                for l in changed:
                    out.append(f"    {l.strip()}")

    _catalogue(out, lib, "instruments",
               "Also in the library, not quoted here. If one of these is what the "
               "prompt asks for, write it yourself in the same spirit:")

    out.append("")
    out.append("## SOUND WORDS (they belong IN the generation, not after it)")
    out.append("What each word means in code. Fold it into how the tone is MADE —")
    out.append("a word is a property of the generator, not an effect bolted on the end.")
    for adj in lib["adjectives"]:
        if not adj.get("code", "").strip():
            continue
        out.append("")
        out.append(f"### {adj['key']} — {adj['why']}")
        out.append(_indent(adj["code"]))

    _catalogue(out, lib, "adjectives",
               "Other words the library knows, without their code:")

    out.append("")
    out.append("## MOTION (movement is code: a free-running oscillator driving a parameter)")
    for mot in lib["motions"]:
        # The heading carries the KIND and the rate. The kind is the whole point of
        # the taxonomy -- does the movement return, is it regular, is it a movement
        # at all -- and the author is its only reader, so leaving it in the data
        # file would make the distinction invisible exactly where it must land.
        # The rate goes here too, not after the prose: a `why` ends in a full stop,
        # and appending ", around 0.19 Hz" to it reads as a typo.
        tag = ", ".join(x for x in (mot.get("kind") or "",
                                    f"around {mot['rate_hz']} Hz" if mot.get("rate_hz") else "")
                        if x)
        out.append("")
        out.append(f"### {mot['key']}{f' ({tag})' if tag else ''} — {mot['why']}")
        if mot.get("code", "").strip():
            out.append(_indent(mot["code"]))

    _catalogue(out, lib, "motions", "Other movements the library knows:")
    return "\n".join(out)



# ─────────────────────────────────────────────────────────────────────────────
# The system prompt — library as orientation, host contract, platform invariants
# ─────────────────────────────────────────────────────────────────────────────
# The invariants are docs/LCO_CONCEPT.md §4. They are user-observable
# fundamentals: the oscillator is a SPECTRUM SOURCE, colour may travel but
# loudness may not, pitch belongs to the synth, and every sound MOVES unless the
# prompt asks for stillness.

_SYSTEM_HEAD = r"""You WRITE Csound orchestra code (Csound 6.18) for a synthesizer's oscillator. You are given a LIBRARY of real, working Csound idioms with measured parameter ranges and plain-language anchors. ADAPT and COMBINE them into the code that generates the sound the user describes. The library orients you; it is not a menu and you are not restricted to it.

WHAT YOU WRITE
Only the oscillator body: the lines that produce the raw signal. The host provides everything around it.

HARD RULES
- Read the pitch from `kfreq` (Hz, k-rate). It GLIDES; everything you write must track it. Never hardcode a pitch or a frequency number.
- Write your final audio into a variable named exactly `asig`.
- Define every variable before you use it, top to bottom. Give your variables distinct names; do not reuse a name for two things.
- Use only real Csound 6.18 opcodes. `vco2`'s imode is an INTEGER (0 saw, 2 pulse, 10 triangle). There is no `vco1`.
- An opcode call has NO equals sign: write `asig poscil 0.6, kfreq` — never `asig = poscil 0.6, kfreq`. `=` is only for arithmetic (`kx = 0.5 + klfo`).
- An opcode STATEMENT names its RESULT VARIABLE first, then the opcode: `ahi atone asig, 2200`. Two consequences you must never break: (a) an opcode that returns audio must have that result variable — `atone asig, 2200` on its own, with nothing on its left, does not compile; (b) the opcode NAME is not a value — never write `aprea = atone`, and never pass a bare `atone`/`rand`/`oscili` as another opcode's argument (`mode rand 0.06, kfreq, kQ` is wrong). To use an opcode's result in an expression, give it its own line first (`ahi atone asig, 2200` then `asig = asig + ahi * 0.3`), or use the functional form WITH parentheses around all arguments (`asig = asig * (1 + oscili(0.18, 5.5, giSine))`).
- `mode` is a resonant FILTER, not an oscillator: `ares mode aexc, kfreq, kQ`. Its first argument is an audio EXCITATION you must define on its OWN line first — `aexc rand 0.06, 0.5, 1` — never a bare opcode inlined (`mode rand 0.06, kfreq, kQ` is wrong). Build a bell/metal/drum bank by driving several `mode` lines from that SAME `aexc`, exactly as the struck_bar, drum_head and cymbal idioms do.
- You shape SPECTRUM and TIMBRE only. Do NOT write an amplitude envelope on the output (no linen, adsr, madsr, expon on the way to `asig`) — loudness belongs to the player's envelope. The COLOUR may travel over the note; the LOUDNESS may not. A tone that fades out on its own is wrong. When a colour movement would drag the level with it (a waveshaper, a filter sweep, a partial fading in), HOLD the level: keep the signal from before the shaping and end with `balance` against it — `alvl = asig` … `asig balance asig, alvl, 40`. Every motion example below does exactly that, and it keeps the loudness inside 0.45 dB while the colour travels freely. Keep that 40: a faster follower (200) starts tracking the waveform itself on bass notes and cancels the very harmonics the drive just made — 10 dB of third harmonic gone at 41 Hz.
- Keep `asig` near +-0.5 peak. The host applies its own headroom and voice gain.
- The sound MOVES by default: a sweep, a beat, a shimmer, a morph. Only write a standing tone if the user explicitly asks for something static or still.
- A LOOP is a free-running `oscili`/`phasor`/`lfo` that NEVER resets, driving a parameter or a crossfade. If the user asks for a loop or for something repeating, write a REPEATING trajectory — never a one-shot `linseg`, which moves once and then holds.
- You may layer up to THREE oscillators and mix them, and you may morph or crossfade between timbres. "a > b" means start at a and move to b; a LOOP of that repeats forever. "a + b" means two layers at once.
- Layer 1 must be scaled by `kvol1`, layer 2 by `kvol2`, layer 3 by `kvol3`, and each layer's pitch is `kfreq * koct1` / `koct2` / `koct3`. Those are the player's mix and octave knobs — a layer that ignores them cannot be mixed. With one layer, use `kvol1` and `kfreq * koct1`.

AVAILABLE IN SCOPE
  kfreq  k-rate pitch in Hz (already glide-smoothed and limited)
  kvel   note velocity 0..1        kpres  pressure/aftertouch 0..1
  ktimb  timbre controller 0..1    knote  seconds since this note started
  kvol1 kvol2 kvol3                per-layer mix (player knobs)
  koct1 koct2 koct3                per-layer octave multiplier (player knobs)
  giSine (sine table)  giCos (cosine table, for gbuzz/buzz)
  giCheb (Chebyshev transfer table)  giImp (short strike impulse table)

OUTPUT FORMAT
Output ONLY Csound code lines. No <CsoundSynthesizer>, no <CsInstruments>, no header (sr/ksmps/nchnls/0dbfs), no `instr`/`endin`, no `ftgen`, no score, no `out`/`outs`/`outch`, no markdown fences, no explanation. The host supplies all of it.

After the code, on ONE final line, write:
READING: <a short plain-language description of what you built, 5-12 words>

LIBRARY (adapt and combine — do not simply copy one block):
"""


def system_prompt(prompt=""):
    """Head + the library entries this prompt reached. The full library stays on
    disk; what travels is the consultation."""
    return _SYSTEM_HEAD + "\n" + render_library(select(prompt))


_REPAIR_PROMPT = (
    "\n\nYour previous attempt did not compile. Csound reported:\n"
    "  {error}\n"
    "Csound's syntax errors are terse, so check the named line against the most "
    "common mechanical causes before rewriting:\n"
    "  - an opcode written with `=` — write `kx linseg ...`, never `kx = linseg ...`; `=` is only for arithmetic.\n"
    "  - an opcode with no result variable (`atone asig, 400` alone), or the opcode NAME used as a value (`aprea = atone`) — every opcode names its result first: `aprea atone asig, 400`.\n"
    "  - an opcode sitting bare inside an expression — give it its own line first, or use its functional form with parentheses.\n"
    "  - `mode` called without a named `aexc` excitation line before it.\n"
    "  - a variable used before it is defined, or your final signal not written into `asig`.\n"
    "Write the WHOLE body again, correctly. Do not explain the error."
)


# ─────────────────────────────────────────────────────────────────────────────
# Sanitising the model's reply
# ─────────────────────────────────────────────────────────────────────────────
# The model is told not to emit a header, a score or an `instr`. It sometimes
# does anyway, and a stray header line would fight the host's own. Strip them
# rather than fail the authoring over a formality; anything that changes the
# SOUND is left untouched.

_STRIP = re.compile(
    r"^\s*(</?Cs\w+|sr\s*=|kr\s*=|ksmps\s*=|nchnls|0dbfs|instr\b|endin\b|"
    r"ftgen\b|\w+\s+ftgen\b|out\b|outs\b|outch\b|i\s+\d|f\s+\d|e\s*$)",
    re.IGNORECASE)

_FENCE = re.compile(r"```[A-Za-z0-9_+#-]*\s*\n(.*?)```", re.DOTALL)
_OUT_CALL = re.compile(r"\s*(?:out|outs|outch)\s+(?:\d+\s*,\s*)?(a\w+)", re.IGNORECASE)
_READING = re.compile(r"^\s*READING\s*:\s*(.+?)\s*$", re.IGNORECASE | re.MULTILINE)


def sanitize(raw):
    """Model reply -> (body, reading). Strips fences, the host's own lines and
    the READING line; recovers `asig` when the model wrote its output through
    `out`/`outch` under another name."""
    txt = raw or ""
    m = _FENCE.search(txt)
    if m:
        txt = m.group(1)
    txt = txt.replace("```", "")

    reading = ""
    rm = _READING.search(txt)
    if rm:
        reading = rm.group(1).strip()
        txt = _READING.sub("", txt)

    kept, captured_out = [], None
    for ln in txt.splitlines():
        s = ln.rstrip()
        if not s.strip():
            continue
        mo = _OUT_CALL.match(s)
        if mo:
            captured_out = mo.group(1)
        if _STRIP.match(s):
            continue
        kept.append(s)
    body = "\n".join(kept)
    # The model routed its signal to the output under another name: keep the
    # sound and give the host the variable it needs.
    if not re.search(r"^\s*asig\b", body, re.MULTILINE) and captured_out and captured_out != "asig":
        body += f"\n  asig = {captured_out}"
    return body, reading


# ─────────────────────────────────────────────────────────────────────────────
# The host scaffold — everything around the authored body
# ─────────────────────────────────────────────────────────────────────────────
# Unchanged from the shipped contract: sr is substituted by the engine at its
# real rate, ksmps=64, nchnls=16 (one channel per voice), one numeric `instr 1`
# with p4 = voice index, six named control channels per voice read via chnget,
# and 16 always-on score instances.

_HEAD = (
    "<CsoundSynthesizer>\n<CsOptions>\n-n -d\n</CsOptions>\n<CsInstruments>\n"
    "sr = %SR%\n"
    f"ksmps = {KSMPS}\n"
    f"nchnls = {NCHNLS}\n"
    "0dbfs = 1\n"
    "giSine ftgen 1, 0, 65536, 10, 1\n"
    # gbuzz reads a COSINE table (its harmonics are cosines); a sine table here
    # would phase-shift every harmonic against the fundamental.
    "giCos  ftgen 2, 0, 65536, 11, 1\n"
    # GEN13 Chebyshev TRANSFER function, odd harmonics with alternating signs:
    # odd-only is antisymmetric, so f(0)=0 and the shaper is DC-free at EVERY
    # drive level and can be swept freely; alternating signs leave each
    # harmonic's magnitude untouched (a sign is a phase) while the peak sums to
    # 0.71 instead of 2.01 — 10 dB of crest given back.
    "giCheb ftgen 3, 0, 8193, 13, 1, 1, 0, 1, 0, -0.5, 0, 0.28, 0, -0.15, 0, 0.08\n"
    # Short decaying harmonic burst: the mallet contact for struck models, which
    # take their strike argument as a TABLE NUMBER, not a scalar.
    "giImp  ftgen 4, 0, 256, 10, 1, 0.5, 0.3, 0.2, 0.1\n"
    # Starting values for the player's mix/octave knobs. The plugin overwrites
    # these from its parameters on the next block; an offline render or a host
    # that never writes them plays exactly what was authored.
    "chnset 1.0000, \"osc1vol\"\n"
    "chnset 1.0000, \"osc1oct\"\n"
    "chnset 1.0000, \"osc2vol\"\n"
    "chnset 1.0000, \"osc2oct\"\n"
    "chnset 1.0000, \"osc3vol\"\n"
    "chnset 1.0000, \"osc3oct\"\n"
    "\n"
    "instr 1\n"
    "  ivoice   = p4\n"
    "  Sgate    sprintf \"gate%d\", ivoice\n"
    "  Sfreq    sprintf \"freq%d\", ivoice\n"
    "  Svel     sprintf \"vel%d\", ivoice\n"
    "  Spres    sprintf \"pres%d\", ivoice\n"
    "  Stimb    sprintf \"timb%d\", ivoice\n"
    "  Strig    sprintf \"trig%d\", ivoice\n"
    "  kgateraw chnget Sgate\n"
    "  kfreqraw chnget Sfreq\n"
    "  kvel     chnget Svel\n"
    "  kpres    chnget Spres\n"
    "  ktimb    chnget Stimb\n"
    "  ktrig    chnget Strig\n"
    "  kvol1    chnget \"osc1vol\"\n"
    "  koct1    chnget \"osc1oct\"\n"
    "  kvol2    chnget \"osc2vol\"\n"
    "  koct2    chnget \"osc2oct\"\n"
    "  kvol3    chnget \"osc3vol\"\n"
    "  koct3    chnget \"osc3oct\"\n"
    "  kgate    portk kgateraw, 0.001\n"
    "  kfreq    limit kfreqraw, 20, 12000\n"
    "  kpresGain = 1.0 + 0.15 * kpres\n"
    # Seconds since THIS note, for anything that shapes timbre over the note.
    # init 0 rather than a settled value: a note whose gate and trig are already
    # high before the first k-cycle gives changed2 no edge to fire on, so a
    # counter starting anywhere else would sit frozen forever.
    "  knote    init 0\n"
    "  if changed2(ktrig) == 1 then\n"
    "    knote  = 0\n"
    "  endif\n"
    "  knote    = knote + 1/kr\n\n"
)

_TAIL = (
    "\n"
    f"  aout     = asig * kgate * kvel * kpresGain * {HEADROOM}\n"
    "  aout     clip aout, 0, 0.95, 0.85    ; final soft peak safety: transparent\n"
    "                                       ; below ~0.8, asymptotes ~0.88 above,\n"
    "                                       ; bounds ANY op stack / crest / host gain\n"
    "  outch    ivoice, aout\n"
    "endin\n"
    "</CsInstruments>\n<CsScore>\n"
)

_SCORE = "".join(f"i 1 0 360000 {v}\n" for v in range(1, NCHNLS + 1)) \
         + "e 360000\n</CsScore>\n</CsoundSynthesizer>\n"


def wrap(body):
    """Authored body -> the full orchestra the engine compiles."""
    indented = "\n".join(("  " + l) if not l.startswith(" ") else l
                         for l in body.splitlines())
    return _HEAD + indented + _TAIL + _SCORE


# ─────────────────────────────────────────────────────────────────────────────
# The compile gate
# ─────────────────────────────────────────────────────────────────────────────

_ANSI = re.compile(r"\x1b\[[0-9;]*m")
_ERR_LINE = re.compile(r"\berror:", re.IGNORECASE)
# Csound points at the offending source two ways: a bare "Line N" for semantic
# errors, and a ">>> <the line> <<<" echo for parse errors. Read both.
_LINE_NO = re.compile(r"^\s*Line\s+(\d+)\s*$", re.IGNORECASE)
_ECHO = re.compile(r">>>\s*(.*?)\s*<<<")
# Where the authored body starts inside the wrapped CSD, so a line number in
# Csound's message can be mapped back to a line the AUTHOR actually wrote. The
# model never sees the wrapper; telling it "line 49" of a file it did not write
# is worse than telling it nothing.
_BODY_OFFSET = _HEAD.count("\n")


def _csound_binary():
    return os.environ.get("T5YNTH_CSOUND", "csound")


def _explain(log, orchestra):
    """Csound's own complaint, plus the line of the AUTHORED body it points at.

    Csound reports positions in the wrapped CSD. The author wrote only the body
    and has never seen the wrapper, so a bare "Line 49" is unusable to it —
    quoting its own line back is what makes the repair round actually repair.
    """
    msgs, quoted = [], []
    csd_lines = orchestra.splitlines()
    for ln in log.splitlines():
        if _ERR_LINE.search(ln):
            # drop Csound's "from file /tmp/....csd (1)," prefix: a temp path is
            # noise in the repair turn, and the author cannot act on it.
            msgs.append(re.sub(r"^.*?from file .*?,\s*", "", ln.strip()))
            continue
        e = _ECHO.search(ln)
        if e and e.group(1).strip():
            quoted.append(f"your line: {e.group(1).strip()}")
            continue
        m = _LINE_NO.match(ln)
        if m:
            n = int(m.group(1))
            src = csd_lines[n - 1].strip() if 0 < n <= len(csd_lines) else ""
            if src and n > _BODY_OFFSET:
                quoted.append(f'your line: {src}')
    if not msgs:
        tail = [l for l in log.strip().splitlines() if l.strip()]
        msgs = [tail[-1]] if tail else ["csound failed without a message"]
    # de-duplicate while keeping order: the same error is often echoed per pass
    seen, parts = set(), []
    for part in msgs + quoted:
        if part not in seen:
            seen.add(part)
            parts.append(part)
    return "; ".join(parts[:4])


def syntax_check(orchestra):
    """(ok, first_error). Runs the real compiler over the real orchestra with
    `--syntax-check-only`, so the gate is Csound's own verdict rather than a
    parser of ours guessing at one. sr is substituted for the check only."""
    csd = orchestra.replace("%SR%", "44100")
    with tempfile.NamedTemporaryFile("w", suffix=".csd", delete=False) as fh:
        fh.write(csd)
        path = fh.name
    try:
        r = subprocess.run([_csound_binary(), "--syntax-check-only", path],
                           capture_output=True, text=True, timeout=90)
        log = _ANSI.sub("", (r.stderr or "") + (r.stdout or ""))
        if r.returncode == 0:
            return True, ""
        return False, _explain(log, orchestra)
    except FileNotFoundError:
        # No compiler on this machine: authoring still works, it is just
        # unverified. Say so rather than failing a good orchestra.
        return True, ""
    except subprocess.TimeoutExpired:
        return False, "csound syntax check timed out"
    finally:
        try:
            os.unlink(path)
        except OSError:
            pass


# ─────────────────────────────────────────────────────────────────────────────
# The entry point
# ─────────────────────────────────────────────────────────────────────────────

def build_csound_response(text, llm, correction="", previous=""):
    """Prompt -> live Csound orchestra. The REAL pipeline entry
    (pipe_inference mode=="csound" calls this).

    ONE inference writes the orchestra body against the library; the compiler
    checks it; a failure goes back to the model with Csound's own error, up to
    MAX_TRIES. There is NO fallback: if the model cannot produce a compiling
    orchestra, this returns ok=false and the LCO stays silent, exactly as
    docs/LCO_CONCEPT.md §4 requires ("no LLM, no oscillator").

    ``llm`` is the caller-injected ``(text, system_prompt, max_new_tokens) ->
    str`` callable. Returns the {ok, orchestra, reading, error} shape the C++
    PipeInference parses.

    ``correction``/``previous`` are accepted for wire compatibility and are
    appended to the user turn when present (the self-listen loop is currently
    deactivated and sends neither).
    """
    prompt = (text or "").strip()
    if not prompt:
        return {"ok": False, "error": "empty prompt"}

    user_turn = prompt
    if correction:
        user_turn = (f"{prompt}\n\nThe previous attempt was described as: "
                     f"{previous}\nCorrect it: {correction}")

    sysp = system_prompt(prompt)
    attempts = []
    turn = user_turn
    for attempt in range(1, MAX_TRIES + 1):
        # No token cap: the orchestra is as long as the sound needs. A cap here
        # would cut the body mid-line, and a truncated generation is not an
        # error — it would arrive as a syntax failure with no cause to show.
        raw = llm(turn, sysp, None)
        body, reading = sanitize(raw)
        if not body.strip():
            attempts.append("the model returned no code")
            turn = user_turn + _REPAIR_PROMPT.format(error="you returned no code at all")
            continue

        orchestra = wrap(body)
        ok, err = syntax_check(orchestra)
        if ok:
            return {"ok": True, "orchestra": orchestra,
                    "reading": reading or _fallback_reading(body),
                    # The panel's transparency surface. Under the write-path the
                    # honest answer to "what did the machine build?" is the code
                    # the model actually wrote -- not a list of keys it picked,
                    # because it picks none.
                    "params_text": body,
                    "attempts": attempt}
        attempts.append(err)
        turn = user_turn + _REPAIR_PROMPT.format(error=err)

    return {"ok": False,
            "error": "the author could not write a compiling orchestra after "
                     f"{MAX_TRIES} attempts: {attempts[-1] if attempts else 'unknown'}",
            "attempts": MAX_TRIES}


def _fallback_reading(body):
    """A reading when the model omitted its READING line. Names the opcodes it
    actually used — a true, if plain, statement about what is running."""
    seen = []
    for op in ("vco2", "foscili", "gbuzz", "buzz", "mode", "oscili", "phasor",
               "rand", "reson", "tablei", "tanh", "balance"):
        if re.search(rf"\b{op}\b", body) and op not in seen:
            seen.append(op)
    return ("built from " + ", ".join(seen[:5])) if seen else "authored orchestra"
